repos:
  - repo: local
    hooks:
      - id: plantuml-generate
        name: Generate PlantUML schemas
        description: Generate PlantUML schemas from puml files
        entry: plantuml
        language: system
        types: [file, plantuml]
