@startuml
hide empty methods

class Person {
    id: UUID
    name: string
}

class User {
    mail: Mail
    passwordHash: []byte
    hashAlgorithm: string
    disabled: bool
    checkPassword(password: string): bool
}

class Teacher {
    interrogation: []Interrogation
    courses(): []Course
    test: string
}

class Student {
    results: []Result
    interrogations(): []Interrogation
    classes: []ClassStudent
    courses(): []Course
    average(course: Course): int
}

class Course {
    id: UUID
    name: String
    parent: Course
    average(): int
    interrogations(): []Interrogation
}

class CourseResponsable {
    id: UUID
    responsible: Teacher
    course: Course
    start: Date
    end: Date
}

class CourseStudent {
    student: Student
    course: Course
    start: Date
    end: Date
}

class Interrogation {
    id: UUID
    name: String
    date: Date
    courses(): []Course
    total(): int
    average(): int
    averagePerCourse(course: Course): int
}

class InterrogationDataPerCourse {
    id: UUID
    course: Course
    interrogation: Interrogation
    total: int
    average(): int
}

class Result {
    student: Student
    interrogation: InterrogationDataPerCourse
    course: Course
    status: Status
    result: int
}

class Class {
    id: UUID
    name: String
    responsable: Teacher
    students: []ClassStudent
}

class ClassStudent {
    class: Class
    student: Student
    level: int
    start: Date
    end: Date
}

class School {
    id: UUID
    name: String
    director: User
    classes: []Class
}

class Organization {
    id: UUID
    name: String
    manager: User
    schools: []School
}

Student *-- Result
Interrogation *-- InterrogationDataPerCourse
Course *-- Course
Course *-- InterrogationDataPerCourse
InterrogationDataPerCourse *-- Result
Course *-- CourseStudent
Student *-- CourseStudent
Class *-- ClassStudent
Student *-- ClassStudent
Teacher *-- Class
Course *-- CourseResponsable
Teacher *-- CourseResponsable

School *-- Class
Organization *-- School
School -- User
Organization -- User

Person <|-- User
Person <|-- Student
User <|-- Teacher
User <|-- Director

@enduml